import Navbar from "./navbar"

export const metadata = {
    title: 'Vote',
    description: 'Generated by create next app',
}
    
export default function RootLayout({
        children,
}: {
        children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="container mx-auto w-screen min-h-screen px-2  ">
                <Navbar />
                {children}                 
            </body>
        </html>
    )
}